[package]
name = "repoctl"
version = "0.1.0"
authors = ["Luca Pizzamiglio"]

[dependencies]
structopt = "0.2"
walkdir = "1.0.7"
ucl = { git = "https://github.com/pizzamig/ucl-rs" }
syslog = "3.3.0"
url = "1.7.0"
